language: rust

sudo: false
cache: cargo

env:
  global:
    secure: t+5CYQLTbenye9PvRKOmnLeOmw9VEEhEWD5Xh39qvfyJ+ROo+RoazuSim47XF8bM22ufm2UndvM+WWLjdck6CmbFvovIADKdwfWcwWwMIesSPr+V9oKIq35o3DyDaTVZzpyICo6r15mjYNgbdQcrcpc9TMCor3dH4Rezq7vuG1r4mG0tFePaUER6+lSv+AJw+A9TazPhamA0xKgbX5/OHFP/EhbLpQzTem83o1RiYDovpZzXm70J603cqK36aLS2QJJSx5TAzxBrxkxaq1mvYzsUPgZOllgq+cIXIsQVqsI/hP5p0l916ExdcPrppDZGSBDGtvXgOBphlDkza12DJXe4FcujJEmshboVxot57SWs/lpnSpQ/PtkPrAyod5p9Z884rAyJ6MuYKOt68eTHgo6YPdWGlJPfMJZM5ifugmnwayyx7sBdD6u5S64/hxXr+HVB46xmNVf98ha5mSsmlOqjZSpxyhAa4ldPzdW4F3HBWvjAB5zx+aJsZp4RtRlqPpVg6FY5vzTGPRV8shPUoifNyItGYgNF5J+h2p1UiDp391cNNeJdkh0S7ix+sntsh9qzehWoaR8r+RqTuIdDhh83iPLnrHcIeu5Zq1gwhVgCKX2zDf4xf8NnQeKqmxJsnyQk4RFYXwXDUTzr4uHCznN9BUCBVSvIcYWam1h8u9E=

notifications:
  email:
    on_success: never
    on_failure: never

script:
- cargo build --verbose --all
- cargo test --verbose --all

deploy:
  provider: releases
  api_key:
    secure: OEG/IkapMUEP5FUj0semFRx/73BMxneuMePoUuS3pqPTVPJzIglP/mylgyp/a3ragYiUeeImzyAAHHT8CLQHS4Mw2PouBq8NJG+5IvOZ9lka31DwofKjnNelZHlRnqXLQfyYOyLE5QirOqxIT2uyCzc6TD1Su0+nA6ytPyRh8GDSkFidnkMPrhD0QmKT7qPcMRqSu8kzBVYJc2irzcg8sZj3RbelH+KL810ajmQBjgPvn5ceXevzsym2h1w+484KLAGZWKEn9WGQX7rI7JUZxNrdP6oA2MATte0ihRyaq2nK+EEwWMeeBYGZlp3xWz4vuqaoCLGjv0+573hHwxMZIicCAtH1Xu/e0lxUDFPeVOMsr8av8yyHi0xwnuJhDNJ2vG7dtzPOQu+JsJC5F6Odgt06oLPQ/tFNqQE+/h/6Tos3W7RCyeuG6EEbztiueJot2zpVCaio7C3cxJtnS2H2laf7CuLRANEAgXnrQ4rOGZP5PiGDBSRirevgTs+UGeRzsPap1dDBVm9Ok3crEV359ZNOEBgV9V0+rEImNaTIdba6LONTRRkoSvCJH0v78QW3WNwnf5Vwt30vXp2Bf/M0i4xSt7SBhjXqMe8/IFDXI57+weEq2CB60FJgeHWCqoDNx95z3UMMaeGzTO7OUhy+IVFbDJ+vKF79oj/k08L5+5k=
  on:
    tags: true
    all_branches: true
  file: target/package/file-utils-$TRAVIS_TAG.crate
  skip_cleanup: true

before_deploy:
- cargo doc
- cargo package

after_deploy:
- cargo publish --token $CARGO_API_KEY
